### ISSUE TITLE
Font generation

### ISSUE THREAD

**Issue by volthouse** [davidkreidler/OpenCO2_Sensor#10]
Hello, with which tool can you generate your own fonts or convert free fonts?

**Comment by davidkreidler** [comment]
Hey @volthouse thanks for reaching out. Its a bit more involved.

First, you can use the the template https://github.com/davidkreidler/OpenCO2_Sensor/blob/main/font/bahn.indd to insert your own font in the right size (3 times).
![image](https://github.com/davidkreidler/OpenCO2_Sensor/assets/13180124/488654e9-e1d2-42af-9f15-efc0f56fc5a1)

Then export it as png and use https://github.com/ayoy/font2bytes to convert it to binary.
./f2b -h 70 -w 47 bahn.png > bahn_big.cpp
./f2b -h 44 -w 29 bahn2.png > bahn_mid.cpp
./f2b -h 22 -w 13 bahn3.png > bahn_sml.cpp

Then import the result into you Arduino\libraries folder esp32-waveshare-epd\src\bahn*.cpp (it needs to be tweaked slightly).

If you have any questions please feel free to reach out.

**Comment by volthouse** [comment]
Thank you for your reply, I apologise for my late reply, I have only just started working on my project again.

I am not familiar with INDD files, is it correct that it is an Adobe InDesign file format? Do I need Adobe software for this?

Many thanks for your help!

**Comment by davidkreidler** [comment]
Yes the format is Adobe InDesign. You can also use any other Grafik Programm to create the Images for your font in the right format for https://github.com/ayoy/font2bytes .
