### ISSUE TITLE
Please add `LICENSE` file to repository

### ISSUE THREAD

**Issue by penyuan** [davidkreidler/OpenCO2_Sensor#19]
Thanks for making this amazing open source CO2 sensor! Just ordered one on Tindie, can't wait to receive it soon. ❤️

Can @davidkreidler please include a `LICENSE` file in this repository? GitHub has [easy steps](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) for doing so, and there are [hardware-specific open source licenses](https://choosealicense.com/non-software/) such as [CERN-OHL-S-2.0](https://choosealicense.com/licenses/cern-ohl-s-2.0/).

Happy to send a Pull Request if helpful. 

Thanks!

**Comment by davidkreidler** [comment]
Hey @penyuan thank you for your purchase! Ive added a MIT licence in this commit: https://github.com/davidkreidler/OpenCO2_Sensor/commit/a705ffd5d7deb6f2e755a6baa1590b5d50c6ddbf

David

**Comment by penyuan** [comment]
> Hey @penyuan thank you for your purchase! Ive added a MIT licence in this commit: [a705ffd](https://github.com/davidkreidler/OpenCO2_Sensor/commit/a705ffd5d7deb6f2e755a6baa1590b5d50c6ddbf)
> 
> David

Awesome, thank you so much! 🙇🏼‍♂️
