### ISSUE TITLE
where to order the sensor SCD40

### ISSUE THREAD

**Issue by volthouse** [davidkreidler/OpenCO2_Sensor#7]
where to order the sensor SCD40?

Thanks Volthouse

**Comment by davidkreidler** [comment]
Hello @volthouse that is depending on how you want to use it.
There are development/breakout boards:
https://www.sparkfun.com/products/18365
https://www.adafruit.com/product/5187
https://sensirion.com/de/produkte/katalog/SEK-SCD41/

Or from [aliexpress](https://de.aliexpress.com/item/1005003974569988.html) **"SCD40 module"**

Its also possible to order the raw Sensor and solder it to a self designed PCB.

There is also the option to order the whole Open CO2 Sensor from [Tindie](https://www.tindie.com/products/davidkreidler/open-co2-sensor/). The next series with 150 devices is expected to arrive in April. Please join the waitlist if you are interested. 

Thanks! David
